### ISSUE TITLE
Fix Direction multithreading race condition

### ISSUE THREAD

**Issue by SadConsole** [thesadrogue/TheSadRogue.Primitives#10]
Pointed out in #6 the `Direction` type has a race condition that can cause problems with `YIncreaseUpwards` that is described below. 

# Known Issues
- Functions using `Direction` can end up in race conditions that end in bad behavior if the `Direction.YIncreasesUpwards` flag is changed when other threads are using functions that directly or indirectly use `Directions`.
    - This is actually not a new issue, as it has always been the case that modifying this value frequently was not the intent of its existence and could cause odd behavior, however it should be outlined since the behavior is changed slightly.
    - In short, toggling the static `YIncreasesUpwards` flag will cause the `DeltaY` values of any direction with a non-zero y-component to change.  Changing those values in the middle of an operation that is using them produces incorrect behavior.
    - This is a symptom of the fact that the grid configuration used by the entirety of the library is controlled by this global variable.  It is the intent that at most this is a value you might toggle to match your grid configuration in some initialization function and then never touch again, and in that use case it isn't a problem.  The issue is if the flag is instead toggled in a multi-threaded environment where multiple threads are in the process of using `Directions`, the behavior will not be as expected.
    - It is possible to use locks/synchronization methods on the library side to account for this, however it would significantly affect performance, which is less than ideal considering it isn't a feature most if any users would need.  The alternative is to disconnect grid "state" entirely, and each function that needs to use functions based on direction must take (optionally) a context.  This would mitigate the issue, as in the case of a multi-threaded environment where you must change `YIncreasesUpwards` you would simply create or use separate grid contexts.
    - If the above issue is something that we want to implement, I propose we create an issue for it and implement it in a separate PR, as the underlying issue was in the previous code and is simply carried over into code implemented in this PR (and is largely independent).  Such a refactor would be significant, and probably deserves its own PR.

# Possible fixes

1. Remove the `set` accessor and add a method named `SetYIncreaseUpwardsUnsafe` where the name has **Unsafe** to indicate there are potential problems using the method. The /// comments should include a note about the problem.

**Comment by Chris3606** [comment]
Suggested fix implemented via 65b050adc889c4f42d033749306dd79f762cc1f6.
