### ISSUE TITLE
Add Built-In Syncing of Spatial Maps to Items which Have a Position Field

### ISSUE THREAD

**Issue by Chris3606** [thesadrogue/TheSadRogue.Primitives#116]
Currently, spatial maps require you to manually keep items at the correct position in the spatial map by calling `Move`.  In the case of objects that have a `Position` field and a `Moved` event, that wouldn't be strictly necessary; if the spatial map can detect this, it could keep things synced automatically.

[This issue](https://github.com/Chris3606/GoRogue/issues/75) (now closed) in GoRogue points to a proposal to solve this.

The main issue would be doing it in an intuitive way which does not cost performance.  Further testing and development is needed; but it should be possible one way or another.

**Comment by Thraka** [comment]
I read through the previous issue and I agree, we should move (pun!!) on this. `Position` property with a `Moved` event. Sounds good to me.
