### ISSUE TITLE
Remove inheritdoc tool and verify XML still generated and captured

### ISSUE THREAD

**Issue by ghost** [thesadrogue/TheSadRogue.Primitives#53]
Need to remove the InheritDoc tool from the projects. After it's removed, make sure of the following:

1. XML is still generated.
2. nupkg has XML

**Comment by Chris3606** [comment]
@Thraka A note here is that while the XML will still be generated, the inheritdoc tags won't be replaced in that XML; that is the responsibility of the IDE still.  This shouldn't be an issue in the general case because VS 2019 supports inheritdoc tags in its documntation display, as does docfx.
