### ISSUE TITLE
Change coding conventions for enum and other types to be .NET friendly

### ISSUE THREAD

**Issue by SadConsole** [thesadrogue/TheSadRogue.Primitives#9]
The current coding conventions use CAPITOLS on enum values and constants. The [.NET design guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines) should be followed.

**Comment by Chris3606** [comment]
We should also consider potentially implementing the editorconfig/standards from the .net corefx repo:
https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md
